#Active Profile
spring.profiles.active=test

spring.application.name=server

# Used to show debug messages from spring security into the terminal
logging.level.org.springframework.security=DEBUG

inkwell.server.jwt.secret-key=jwtKey
inkwell.server.jwt.token-duration=3600000